myFive/appFive/urls.py
from django.conf.urls import url
from appFive import views

# Template URl, need to set up the app name

app_name='appFive'

urlpatterns =[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),

]

myFive/myFive/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from appFive import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^appFive/',include('appFive.urls')),
    url(r'^logout/',views.user_logout,name='logout'),
    url(r'^special/',views.special,name='special')


]

myFive/appFive/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    #sentence above is the 1to1 relationship with user in bracket

    # additional class

    portfolio_site = models.URLField(blank=True)
    # it  is okay to keep it blank
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username
  #username is the default User atrribute

myFive/appFive/forms.py
from django import forms
from django.contrib.auth.models import User
from appFive.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

myFive/appFive/views.py
from django.shortcuts import render
from appFive.forms import UserForm,UserProfileInfoForm
# Create your views here.

# import for login logout
from django.contrib.auth import authenticate, login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required



def index(request):
    return render(request,'appFive/index.html')

#note login_required is imported from decorator above

@login_required
def special(request):
    return HttpResponse("You are loggedin, nice")

#to makesure the only user has account can user_logout
# this can be done by decorator
#makesure its 1 line above the function
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered= False
    # if there is a request:
    if request.method == "POST":
        # this imports the form from the forms.py
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            # Save User Form to Database
            user = user_form.save()
            # Hash the password
            user.set_password(user.password)
            # Update with Hashed password
            user.save()

            #commit=False means we dont save data directly to databse
            #
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user =user
            # senetence abve define the 1to1 relationship
            #from modesl.py

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            # Now save model
            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    # refer to te top if statement
    # else if no request:
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

        # Note
        # in registration.html we need user_form, profile_form, and registered
        # logic, so remember to pass them to html
    return render(request,'appFive/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})



def user_login(request):
    if request.method =="POST":
        username = request.POST.get('username')
        # since in the login.html, there is  input called "username"
        # you can grab that using the get method
        password = request.POST.get('password')

        user = authenticate(username=username,password =password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
                # redirect user back to home page
            else:
                return HttpResponse("Acoount not active")
        else:
            print("Username:{} and password {}".format(username,password))
            return HttpResponse("invalid login")
    else:
        return render(request,'appFive/login.html',{})

myFive/templates/appFive/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <nav class='navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class='nav navbar-nav'>
          <li><a class='navbar-brand' href="{%url 'index' %}">Django</a></li>
          <li><a class='navbar-link'  href="{%url 'admin:index' %}">Admin</a></li>
          <li><a class='navbar-link'  href="{%url 'appFive:register' %}">Register</a></li>

          <!-- extra code for login -->
          {% if user.is_authenticated %}
          <!-- go to views.py, user_login fucntion -->
          <!-- referring to user = authenticate() line -->
            <li><a class='navbar-link' href="{%url 'logout' %}">Logout</a></li>
            <!-- under project urls.py you can
            find the line    url(r'^logout/',views.user_logout,name='logout'),
          thats why we have ''logout' here -->
          {% else %}
          <li><a class='navbar-link' href="{%url 'appFive:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block%}
      {%endblock%}
      
    </div>

  </body>
</html>

myFive/templates/appFive/index.html
{%extends "appFive/base.html" %}
{%block body_block%}

<div class="jumbotron">
  <h1>Django Level Five</h1>
</div>

{% endblock%}

myFive/templates/appFive/login.html
{%extends 'appFive/base.html' %}
{% block body_block%}

<div class="jumbotron">
  <h1>Please login</h1>
  <form class="" action="{%url 'appFive:user_login' %}" method="post">
    {% csrf_token %}
    <!-- for any form, you need csrf  -->
    <label for="username">Username</label>
    <input type="text" name="username" placeholder="Enter username">

    <label for="passowrd">Password</label>
    <input type="password" name="password" >

    <input type="submit" name="" value="login">
  </form>
</div>

{%endblock%}

myFive/templates/appFive/registration.html
{% extends "appFive/base.html" %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}